### PR TITLE
`oa_ngrams` speed up with new `{curl}` v5.0.0

### PR DESCRIPTION
**Pull request by yjunechoe**
The [new curl release today](https://ropensci.org/blog/2023/01/13/curl5-release/) adds the parallelized `multi_download()` function, which we can use to significantly speed up `oa_ngrams()` which currently requests/parses one-by-one (we can't do a batch request like in `oa_fetch()` because the ngrams API is async and static).

I'm leaving this as a draft until we decide whether we should:
1) Import `curl` >=5.0.0, OR
2) Import `curl` without version spec as we do currently, but use `multi_download()` if pkg version is >=5.0.0

Until we resolve that, the newer/faster version is added to this draft PR as `oa_ngrams2()`:

```r
devtools::load_all()

# Single paper ngram search ####

single <- "W1963991285"

system.time(ngram_single1 <- oa_ngrams(single))
#> user  system elapsed 
#> 0.02    0.01    0.18 
#> 
system.time(ngram_single2 <- oa_ngrams2(single))
#> user  system elapsed 
#> 0.03    0.00    0.17 

identical(ngram_single1, ngram_single2)
#> [1] TRUE


# Many paper ngram search ####

batch <- oa_snowball(single)$nodes$id
length(batch)
#> [1] 348

system.time(ngram_batch1 <- oa_ngrams(batch))
#> user  system elapsed 
#> 10.24    1.75   85.71 

system.time(ngram_batch2 <- oa_ngrams2(batch))
# user  system elapsed 
# 7.82    1.03   13.25 

identical(ngram_batch1, ngram_batch2)
#> [1] TRUE
```

### CODE REVIEW

**Comment by trangdata** [comment]
Exciting stuff, @yjunechoe!!! 🚀  The speed-up is impressive!

For now, I think I'm leaning toward option 2: Import curl without version spec as we do currently, but use multi_download() if pkg version is >=5.0.0. Perhaps we could add a one-time message in `oa_ngrams` to recommend the user update their curl installation. What do you think?

**Comment by yjunechoe** [comment]
I think I'm leaning towards that as well and printing a message is a good compromise! Let me see how much of the code I can recycle to have one `oa_ngrams()` that can flip between the two versions

**Comment by yjunechoe** [comment]
Ok, back to having a single `oa_ngrams()` which uses the faster implementation if `curl >= v5` and falls back to old implementation if not.

Not sure if this is the most principled/idiomatic way to do this but the "one-time message" is implemented via global options (`"oa_ngrams.message.curlv5"`).

**Review by trangdata — APPROVED** [review]
Looks great to me @yjunechoe! 🎉  Please feel free to merge! (Do you have write access yet? If not, @massimoaria, could you add June, please? Thank you! 🌈 )

**Comment by yjunechoe** [comment]
Accidentally left out a line that removes the downloaded data from tempdir but it's back in now so should be good!

**Pull request merged**
